service: daily_games_score
image: hhassig/daily-games-score
servers:
  web:
    hosts:
      - 100.97.138.69
    env:
      DB_HOST: daily_games_score-db
      SOLID_QUEUE_IN_PUMA: "true"
proxy:
  ssl: true
  host: dgs.hassig.com
registry:
  username: hhassig
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - DAILY_GAMES_SCORE_DATABASE_PASSWORD
    - TELEGRAM_API_KEY
    - KAMAL_REGISTRY_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    POSTGRES_USER: daily_games_score
    POSTGRES_DB: daily_games_score_production
    POSTGRES_HOST: daily_games_score-db
    POSTGRES_PORT: 5432
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "daily_games_score_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
accessories:
  db:
    image: postgres:16
    host: 100.97.138.69
    port: 5436:5432
    env:
      clear:
        POSTGRES_USER: daily_games_score
        POSTGRES_DB: daily_games_score_production
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /srv/daily_games_score/postgres-data:/var/lib/postgresql/data
      - /srv/daily_games_score/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
